import http.server
import socketserver
from urllib.parse import urlparse
from urllib.parse import parse_qs

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        # Extract query param
        a = 1
        b = 1

        query_components = parse_qs(urlparse(self.path).query)
        if 'a' in query_components:
            a = int(query_components["a"][0])

        if 'b' in query_components:
            b = int(query_components["b"][0])

        produs = a * b

        # Some custom HTML code, possibly generated by another function
        html = f"<html><head></head><body><h1>Produsul a * b  = {produs}!</h1></body></html>"

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return

# Create an object of the above class
handler_object = MyHttpRequestHandler

PORT = 8000
my_server = socketserver.TCPServer(("", PORT), handler_object)

# Star the server
my_server.serve_forever()